### PR TITLE
Properly parse carddav address-data - fixes #1017

### LINKED ISSUE #1017: Woops, something's gone wrong! The CardDAV server returned the http status code 500.
I use sabre-dav in combination with z-push (http://z-push.org/).
Since the update of sabre-dav from 3.2.0 to 3.2.1, z-push is broken and I get error messages like the following in the z-push log:

```
06/12/2017 22:47:48 [ 5484] [ INFO] [unknown] ExportChangesDiff->InitializeExporter(): Found '1' changes for 'contacts'
06/12/2017 22:47:49 [ 5484] [ERROR] [unknown] BackendCardDAV->GetMessage - Error getting vcard 'a4de694e-60c3-4a50-b504-bd2641d3b2a4' in '7f7297f2': Woops, something's gone wrong! The CardDAV server returned the http status code 500.
06/12/2017 22:47:49 [ 5484] [ERROR] [unknown] BackendCardDAV->GetMessage(): vCard not found
06/12/2017 22:47:49 [ 5484] [WARN] [unknown] C:\src\z-push\src\lib\default\diffbackend\exportchangesdiff.php:163 Creating default object from empty value (2)
```
Running a git bisec points at 73065c3273cc517e201354b06d3918c88d755d99 as the first faulty commit. This was added for #889

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by staabm** [comment]
just curious: did you intenionally not cherry pick/merge this commits?

**Comment by DeepDiver1975** [comment]
> just curious: did you intenionally not cherry pick/merge this commits?

I did cherry-pick this last week together with the other PR #1027 - but I simply did forget to open the PR ;-)

**Comment by staabm** [comment]
hmm ok, wondered why the git hashes are different then. I had the impression those should be equal after cherry picking, but I might be wrong.

**Comment by DeepDiver1975** [comment]
> hmm ok, wondered why the git hashes are different then. I had the impression those should be equal after cherry picking, but I might be wrong.

no - the hashes change on cherry-pick.

But as we speak - I just reminded myself that usually merge across all branches was used in the past. I'm not that familiar with this type of repo handling.

Should we keep the old mechanism? I don't want to dictate the way I'm used to work on here.

**Comment by staabm** [comment]
I also have no preference and dont know whether there are benefits of doing it like one way or the other.

**Pull request merged**
