### PR TITLE
feat: use php7.4 as minimum

### PR DESCRIPTION
**Pull request by DeepDiver1975**
refs #1415

### CODE REVIEW

**Comment by phil-davis** [comment]
@DeepDiver1975 there were 1807 unit tests running - for exampe https://github.com/sabre-io/dav/actions/runs/6862503131/job/18660341581 
But only 887 unit tests have run in gthis PR: https://github.com/sabre-io/dav/actions/runs/6856309480/job/18643234604?pr=1502

Maybe renaming various test file to `TestAbstract.php` has caused that?

**Comment by DeepDiver1975** [comment]
I will look into this.

**Comment by DeepDiver1975** [comment]
@phil-davis we have now 1640 tests. Previously test within sabre/http were executed as well - but they no longer exist in the composer package. This is fine form my pov as it is no the job of sabre/dav to run sabre/http tests

**Comment by phil-davis** [comment]
> Previously test within sabre/http were executed as well
'
I had wondered why that was done, but without knowing the history I didn't like to stop running those sabre/http tests.

**Review by phil-davis — APPROVED** [review]
LGTM

**Comment by phil-davis** [comment]
I will merge and we can progress from here towards a major version with type declarations etc.

**Pull request merged**
