### PR TITLE
declare addressDataProperties to avoid PHP 8.2 deprecation notice

### PR DESCRIPTION
**Pull request by phil-davis**
Issue #1445 

declare addressDataProperties to avoid PHP 8.2 deprecation notice

This is the easy fix that I can see for one of the things mentioned in the issue.

### CODE REVIEW

**Review by staabm — COMMENTED** [review]
Lgtm - can this be covered by a test?

**Comment by antiftw** [comment]
Any chance this might be merged in the near future? I just spent a day wondering and trying to figure out why DavX5 would not sync contacts anymore with my Baikal server after a reinstall. 

Have now manually "fixed" the error by editing the code in the vendor map, but it would be nice for this to be merged to prevent issues in the future. Especially since it seems quite a low impact merge. Or I might be mistaken?

Thanks.

**Comment by jschwender** [comment]
I can confirm, that in my case this requested merge fixed the issue of broken synchronizing. I am running baikal 0.9.3 on Debian 12.0, with php 8.2 and DAVX5 4.3.4.1-ose on android 11. Now it works again (for me). Maybe that helps.

**Comment by Yannik** [comment]
@phil-davis Would you mind merging this? :-)

**Comment by tbba** [comment]
Please update.

**Comment by ByteHamster** [comment]
I just solved the merge conflict. @phil-davis, what is the status of this PR? I'm getting quite a few bug reports about this over at Baikal. Can we get it merged? It does not look like it could break anything

**Review by DeepDiver1975 — APPROVED** [review]

**Comment by ByteHamster** [comment]
Thanks @DeepDiver1975! Should I prepare a release commit like 29185248264ff0b5fc70d784f920d67d57d702de for sabre/dav, so we can get this change into Baikal?

**Comment by DeepDiver1975** [comment]
Let's discuss with @phil-davis and @staabm if there is more to be added. TBH I lost the track a bit in here .....

**Pull request merged**
