### PR TITLE
Hello GitHub actions

### PR DESCRIPTION
**Pull request by kesselb**

### CODE REVIEW

**Comment by kesselb** [comment]
Hey @phil-davis @DeepDiver1975 :wave: 

As example run: https://github.com/kesselb/dav/pull/1

**Comment by phil-davis** [comment]
@staabm ping to remove travis required status.

**Comment by staabm** [comment]
@phil-davis done

**Review by phil-davis — APPROVED** [review]
Looks reasonable. It should do something similar to the previous Travis CI matrix. Let's merge and see what runs.

**Pull request merged**
