### PR TITLE
Add logging example implementation to groupwareserver

### PR DESCRIPTION
**Pull request by Yannik**
As per #806

### CODE REVIEW

**Comment by phil-davis** [comment]
@Yannik this needs some formatting to keep `php-cs-fixer` happy - see Travis CI fails https://travis-ci.org/sabre-io/dav/jobs/646593845?utm_medium=notification&utm_source=github_status

**Comment by Yannik** [comment]
@phil-davis Should be fixed now.

**Comment by DeepDiver1975** [comment]
> @phil-davis Should be fixed now.

actually not - see travis output

**Comment by Yannik** [comment]
@DeepDiver1975 
I think this is a `php-cs-fixer`  error.
Firstly, I'd like to note that this change was not suggested by PHPStan during the earlier  (OP) build (https://travis-ci.org/github/sabre-io/dav/jobs/646593845)

Secondly, please have a look at the suggested change (https://travis-ci.org/github/sabre-io/dav/jobs/677680657):

```
-/**
+/*
```

This doesn't really make sense in that place. All the other comments are of format `/**`, too.

**Comment by phil-davis** [comment]
CI is failing in all PRs - I raised issue #1266 
I will look.

**Comment by DeepDiver1975** [comment]
Please rebase

**Pull request closed without merging**
