### PR TITLE
Add check for Lock-Token in request header.

### PR DESCRIPTION
**Pull request by datatrippers**
Only check for Lock-Token is there are $mustLocks left.
This applies for PUT requests, which used to fail when saving from Word 2016

### CODE REVIEW

**Comment by staabm** [comment]
could you add a unit test to show your issue?

**Comment by datatrippers** [comment]
I've copied the MSWord unit test and updated the PUT request with the LockToken header.

Attached you'll find the put request

[PUT request Word2016.txt](https://github.com/fruux/sabre-dav/files/1142496/PUT.request.Word2016.txt)

**Comment by PVince81** [comment]
@davitol this explains why it didn't work back then when testing and where you had to switch to using "If"

**Comment by DeepDiver1975** [comment]
word202 :zzz: -> close

**Pull request closed without merging**
