### PR TITLE
Release 3.1.5

### PR DESCRIPTION
**Pull request by DeepDiver1975**
refs #1097

### CODE REVIEW

**Comment by staabm** [comment]
Builds fail. I guess we missed a dependency update or similar?

**Comment by DeepDiver1975** [comment]
fails with sabre/http 4.2.4 and suceeds with 4.2.1

reason: https://github.com/sabre-io/http/pull/70

**Comment by DeepDiver1975** [comment]
@staabm fixed - we can ignore prettyci failure here

**Comment by staabm** [comment]
Thx

**Pull request merged**
