### PR TITLE
Fix for #572

### PR DESCRIPTION
**Pull request by evert**

### CODE REVIEW

**Comment by RealRancor** [comment]
@evert As a follow-up of https://github.com/owncloud/android/issues/1074 and https://github.com/owncloud/core/issues/13786:

Seems that fix should have been included in 2.1.2:

https://github.com/fruux/sabre-dav/blob/3.1.1/CHANGELOG.md#212-2014-12-10

but never made it into that release.

**Comment by AnrDaemon** [comment]
I'd echo the same request. We just [got hit by this very issue](http://forum.ubuntu.ru/index.php?topic=271478.msg2168758#msg2168758) and the proposed change indeed resolved the problem the user was having.

**Comment by evert** [comment]
I'm fairly sure that that change got reverted later, because it was a BC break.

**Comment by AnrDaemon** [comment]
Does that mean that mobile clients are useless right now?

**Comment by evert** [comment]
I'm not sure I understand your question. This ticket refers to a very specific issue. It got reverted later, but a new solution _was_ added on the 2.1 branch. The more correct fix got added in 3.0, but afaik this should not be a problem in stock sabre/dav on the 2.1 branch.

If this is causing a new problem, please just open a new ticket with a reproducible test case. "It causes an error on owncloud" is not enough information for me to figure out what's wrong. If it's an issue in owncloud, open a ticket on that project, not here.

**Comment by AnrDaemon** [comment]
The issue is still present in ownCloud 8.2.3, the solution from this PR still works.

**Comment by evert** [comment]
Then you should report the issue at Owncloud. I'm locking this thread now.

**Pull request merged**
