### PR TITLE
Add sender name in invite mail headers

### PR DESCRIPTION
**Pull request by benrubson**
Hi,

This tiny PR adds the sender name in Cal invite mail headers.

Thank you 👍

### CODE REVIEW

**Comment by benrubson** [comment]
@ByteHamster may I ask you to review this PR if you're OK ?
Many thanks 👍

**Comment by DeepDiver1975** [comment]
Can you please squash the commits?

And i will Research If we need to escape the Name to Not allow some HTML injection .... I have Seen Something related .... 🤷

**Comment by benrubson** [comment]
> Can you please squash the commits?

Just done, thank you 👍

**Comment by DeepDiver1975** [comment]
> And i will Research If we need to escape the Name to Not allow some HTML injection .... I have Seen Something related .... 🤷

Not directly related to this PR .... but worth a look - https://blog.ripstech.com/2017/why-mail-is-dangerous-in-php/

Furthermore we should consider to use e.g. swiftmailer since it implements a lot of escaping and validation on email headers ... see https://github.com/swiftmailer/swiftmailer/tree/master/lib/classes/Swift/Mime/Headers

**Comment by benrubson** [comment]
Regarding `iTipMessage->senderName` itself, perhaps it is already sanitized before in the code (along with `senderEmail`) ?

**Comment by benrubson** [comment]
Thank you all 👍

**Pull request merged**
