### PR TITLE
Export to xCal

### PR DESCRIPTION
**Pull request by Hywan**
Depends on #606, it must be merged before this one.

This PR allows one to use `ICSExportPlugin` to export to xCal.

### CODE REVIEW

**Comment by evert** [comment]
Needs a test still

**Comment by Hywan** [comment]
Oh yes sure, will do that soon :-).

**Comment by Hywan** [comment]
> will do that soon

“soon”

…

Sorry. Still releveant?

**Comment by DeepDiver1975** [comment]
> Sorry. Still relevant?

I guess not -> close

**Pull request closed without merging**
