### PR TITLE
Fix wrong return Type, backport #1106

### PR DESCRIPTION
**Pull request by micbar**
The PHP doc needs to be correct, phan tests fail.

### CODE REVIEW

**Comment by staabm** [comment]
I dont think changes is worth beeing backported.

**Comment by DeepDiver1975** [comment]
> I dont think changes is worth beeing backported.

we have been falling over this in the contact of owncloud and using phpstan ...

**Comment by DeepDiver1975** [comment]
@micbar pretty ci is to be ignored on this branch - styles only apply to master branch as of now

**Comment by micbar** [comment]
ok, thanks for the hint

**Comment by staabm** [comment]
> we have been falling over this in the contact of owncloud and using phpstan ...

I see.

here we go.

**Pull request merged**
