### PR TITLE
Remove sabre/cs

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@staabm any idea why the prettyci check is not popping up? :confused:

**Comment by staabm** [comment]
@DeepDiver1975 thx check seems to run now

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 the check seems to run now

We need to review the print out and see if we agree or need to adapt the config

**Comment by staabm** [comment]
as stated elsewhere: I dont prefer any style and would welcome any "standard open source style", like e.g. the symfony you configured.

evert also wasn't fixed on the old style.

in case this fits for you we can go ahead.

**Pull request merged**
