### PR TITLE
[tests-only] Investigate CI

### PR DESCRIPTION
**Pull request by phil-davis**
Just checking if the latest tool dependencies are passing.

### CODE REVIEW

**Comment by phil-davis** [comment]
https://travis-ci.org/github/sabre-io/dav/jobs/740100574
```
$ psql -c "create database sabredav_test" -U postgres

psql: error: could not connect to server: could not connect to server: No such file or directory

	Is the server running locally and accepting

	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

The command "psql -c "create database sabredav_test" -U postgres" failed and exited with 2 during .
```

Looking...

**Comment by phil-davis** [comment]
https://travis-ci.org/github/sabre-io/dav/jobs/738448268 on 2020-10-24
```
$ mysql -u root -h 127.0.0.1 -e 'create database sabredav_test'
$ psql -c "create database sabredav_test" -U postgres
CREATE DATABASE
$ psql -c "create user sabredav with PASSWORD 'sabredav';GRANT ALL PRIVILEGES ON DATABASE sabredav_test TO sabredav" -U postgres
GRANT
```

It could do `psql` command to create the database and user.

But now it has broken. But there are no changes in `master`. So "something happened" in Travis???

**Comment by staabm** [comment]
Sounds like a travisci bug?

**Comment by phil-davis** [comment]
I emailed Travis support - let's see in the next day or 2.

**Comment by phil-davis** [comment]
There was no response. I did https://github.com/sabre-io/dav/pull/1305/files - switched the PHP 8.0 pgsql back from Ubuntu 20.04 to 18.04 and it "just worked"

**Pull request closed without merging**
