### PR TITLE
Allow nesting of trees

### PR DESCRIPTION
**Pull request by icewind1991**
Makes `Tree` implement `ICollection` and modify `getNodeForPath` to pass the request to nested trees.

My main use case for this in Nextcloud is that for part of the tree we can optimize `getNodeForPath` by directly getting the target node instead of going trough all parent nodes, but there is currently no clean way to apply this optimization to only a part of the dav tree.
With nested trees we could put this optimization in a separate `Tree` subclass and nest it into the "main" tree.

### CODE REVIEW

**Comment by evert** [comment]
I've been considering doing this exact thing for a while, because it kind of allows for a sort of 'mounting' type of system.

However,  the methods having multiple purposes (`delete()` vs `delete($path)`) makes me feel a bit uncomfortable.

So one thing I'm wondering is, could it make sense to instead just add a new interface that only defines the `getNodeForPath()` function. (or maybe `getChildByPath()`, idk), or does that not satisfy your use-case?

**Comment by icewind1991** [comment]
I'm also not a fan of the method name conflicts.

A separate interface for just the `getNodeForPath` would probably cover the specific use case I started the work for but having full nesting of trees would most likely be useful in future cases (I'm fairly sure it would allow us to do some good code reuse)

**Comment by icewind1991** [comment]
True.

I would go for `getNodeForPath` instead of `getChildByPath` or something similar because then `Tree` can simply implement the new interface.

I'll look into implementing this tomorrow

**Comment by DeepDiver1975** [comment]
@icewind1991 let's revive this once work continues on #1060

**Comment by DeepDiver1975** [comment]
@icewind1991 rebase and move on? :wink:

**Comment by DeepDiver1975** [comment]
feel free to reopen if this is still of interest

**Pull request closed without merging**
